name: Continuous Integration
description: This workflow runs pre-commit checks, lints, typechecks, builds the application, and validates conventional commits on pull requests.

on:
  pull_request:
  push:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck-and-build:
    name: Typecheck and Build
    uses: ./.github/workflows/build.yml

  pre-commit:
    name: Pre-commit Checks
    uses: ./.github/workflows/pre-commit.yml

  commits:
    name: Conventional commit validation
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/conv-commits.yml
